name: HubCore
version: 1.0.0
main: shadow\Loader
api: 5.0.0
author: 404_Shad0w
depend:
  - QueueAPI
  - QueryAPI

permissions:
  player.perms:
    description: Permission to use player commands
    default: true
  admin.perms:
    description: Permission to use admin commands
    default: op
  cosmetics.command:
    description: Allows the player to use the cosmetics command
    default: true
  cosmetics.cape:
    description: Allows the player to equip a cape
    default: true
  cosmetics.wings:
    description: Allows the player to equip wings
    default: true
  cosmetics.bandana:
    description: Allows the player to equip a bandana
    default: true